"""empty message

Revision ID: 0d3e4c50a785
Revises: 33b50aee8664
Create Date: 2021-03-24 03:50:49.581012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3e4c50a785'
down_revision = '33b50aee8664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_notifications', sa.Column('user_connection_id', sa.Integer(), nullable=False))
    op.drop_constraint('chat_notifications_sender_user_id_fkey', 'chat_notifications', type_='foreignkey')
    op.create_foreign_key(None, 'chat_notifications', 'user_connections', ['user_connection_id'], ['id'])
    op.drop_column('chat_notifications', 'sender_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_notifications', sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_notifications', type_='foreignkey')
    op.create_foreign_key('chat_notifications_sender_user_id_fkey', 'chat_notifications', 'user_connections', ['sender_user_id'], ['id'])
    op.drop_column('chat_notifications', 'user_connection_id')
    # ### end Alembic commands ###
