"""update

Revision ID: 18115f6a3d92
Revises: 95006bda00db
Create Date: 2021-03-24 02:00:45.802760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18115f6a3d92'
down_revision = '95006bda00db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_notifications', sa.Column('user_connection_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_notifications', 'user_connections', ['user_connection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_notifications', type_='foreignkey')
    op.drop_column('chat_notifications', 'user_connection_id')
    # ### end Alembic commands ###
