"""add sender user id

Revision ID: d0eda29ada4e
Revises: 3f361790c968
Create Date: 2021-03-24 01:26:14.385670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0eda29ada4e'
down_revision = '3f361790c968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_notifications', sa.Column('sender_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chat_notifications', 'users', ['sender_user_id'], ['id'])
    op.drop_column('chat_notifications', 'recipient_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_notifications', sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_notifications', type_='foreignkey')
    op.drop_column('chat_notifications', 'sender_user_id')
    # ### end Alembic commands ###
